# requirements.yaml
dependencies:
- name: jupyterhub
  version: "1.1.3"
  repository: 'https://jupyterhub.github.io/helm-chart/'
- name: mariadb
  version: ">=9.3.5"
  repository: "https://charts.bitnami.com/bitnami/"
- name: nfs-server-provisioner
  version: "1.4.0"
  repository: "https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/"