{{- $root := . -}}

{{- if index .Values "nfs-pvcs" -}}
{{ range $key, $value := index .Values "nfs-pvcs" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ index $value "name" }}
spec:
  {{- with index $root.Values "nfs-server-provisioner" }}
  storageClassName: {{ .storageClass.name }}
  {{- end }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
{{- end -}}
{{ end }}