apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-pre-start-config-map
data:
{{- if .Values.ssh.pre_ssh_start }}
{{- range $key, $value := .Values.ssh.pre_ssh_start }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- else}}
  none.sh: |
{{- end }}
