apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config-map
data:
  sshd_config_jump: |
    {{- range $key, $value := .Values.ssh.config.jump.sshd_config }}
    {{ $key }} {{ $value }}
    {{- end }}
  ssh_config_jump: |
    {{- range $key, $value := .Values.ssh.config.jump.ssh_config }}
    {{ $key }} {{ $value }}
    {{- end }}
  sshd_config_user: |
    {{- range $key, $value := .Values.ssh.config.user.sshd_config }}
    {{ $key }} {{ $value }}
    {{- end }}
  ssh_config_user: |
    {{- range $key, $value := .Values.ssh.config.user.ssh_config }}
    {{ $key }} {{ $value }}
    {{- end }}
