kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: "pufsalad"
  region: "us-west-2"
  version: "1.18"
availabilityZones: ["us-west-2b", "us-west-2c", "us-west-2d"]
managedNodeGroups:
  - name: "service-nodes-2d"
    instanceType: t3.medium
    availabilityZones: ["us-west-2d"]
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      dirac.institute/instance-type: "service"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/dirac.institute/instance-type: "service"
  - name: "notebook-nodes-2d"
    instanceType: t3.xlarge
    availabilityZones: ["us-west-2d"]
    minSize: 1
    maxSize: 16
    desiredCapacity: 1
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      dirac.institute/instance-type: "notebook"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/dirac.institute/instance-type: "notebook"
  - name: "spark-nodes-2d"
    instanceType: t3.xlarge
    spot: true
    availabilityZones: ["us-west-2d"]
    minSize: 1
    maxSize: 128
    desiredCapacity: 1
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      dirac.institute/instance-type: "spark"
    tags:
      k8s.io/cluster-autoscaler/node-template/label/dirac.institute/instance-type: "spark"


